services:
  site:
    build: ./frontend
    network_mode: "host"
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /frontend
          ignore:
            - node_modules/
        - action: rebuild
          path: ./frontend/package.json
    depends_on:
      - server

  server:
    build: ./backend
    network_mode: "host"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - db

  db:
    image: postgres:18.2-alpine
    container_name: fashionstore_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fashionstore
      POSTGRES_DB: fashion_store
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fashion_store"]
      interval: 1s
      timeout: 5s
      retries: 10
