package ca.mcgill.ecse321.fashionstore;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/** This source class was generated by the Gradle 'init' task. */
@SpringBootApplication
public class FashionStoreApplication {
    /** This source method was generated by the Gradle 'init' task. */
    public static void main(String[] args) {
        SpringApplication.run(FashionStoreApplication.class, args);
    }
}
