package ca.mcgill.ecse321.fashionstore;

import ca.mcgill.ecse321.fashionstore.model.Owner;
import ca.mcgill.ecse321.fashionstore.repository.OwnerRepository;
import java.util.List;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/** This source class was generated by the Gradle 'init' task. */
@SpringBootApplication
public class FashionStoreApplication {
    /** Setup method for FashionStoreApplication. */
    public static void main(String[] args) {
        SpringApplication.run(FashionStoreApplication.class, args);
    }

    /**
     * Create owner once the entire application context has successfully started.
     *
     * @author Cyrus Fung (cfung89)
     */
    @Bean
    public CommandLineRunner createOwner(OwnerRepository ownerRepository) {
        return args -> {
            List<Owner> owners = ownerRepository.findAll();
            if (owners.isEmpty()) {
                Owner owner = new Owner();
                owner.setEmail("admin@fashionstore.com");
                owner.setPassword("security");
                ownerRepository.save(owner);
            }
        };
    }
}
