package ca.mcgill.ecse321.fashionstore.repository;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;

import ca.mcgill.ecse321.fashionstore.model.ClothingItem;
import ca.mcgill.ecse321.fashionstore.model.Customer;
import ca.mcgill.ecse321.fashionstore.model.Order;
import java.sql.Date;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.transaction.annotation.Transactional;

/** This source class was generated by the Gradle 'init' task. */
@SpringBootTest
class CustomerRepositoryTests {

    /** This source method was generated by the Gradle 'init' task. */
    @Test
    void contextLoads() {
        assertDoesNotThrow(() -> {});
    }

    @Autowired private CustomerRepository customerRepository;
    @Autowired private OrderRepository orderRepository;
    @Autowired private ClothingItemRepository clothingItemRepository;
    @Autowired private ClothingProductRepository clothingProductRepository;
    private Customer customer;

    /**
     * Create a customer in the database before each test.
     *
     * @author Jennifer You (jenni4u)
     */
    @BeforeEach
    public void createCustomer() {
        Customer newCustomer = new Customer();
        newCustomer.setEmail("mimi@kittycat.com)");
        newCustomer.setPassword("meowmeow");
        newCustomer.setAddress("123 Cat Street");
        newCustomer.setNumLoyaltyPoints(100);
        customerRepository.save(newCustomer);

        // save customer reference for tests
        customer = newCustomer;
    }

    /**
     * Clear up databases after each test.
     *
     * @author Jennifer You (jenni4u)
     */
    @AfterEach
    public void clearDatabase() {
        customerRepository.deleteAll();
        orderRepository.deleteAll();
        clothingItemRepository.deleteAll();
        clothingProductRepository.deleteAll();
    }

    /**
     * Test read and write of the Customer object in the persistence layer.
     *
     * @author Jennifer You (jenni4u)
     */
    @Test
    void testCustomerLoad() {
        assertNotNull(
                customerRepository.findCustomerByEmail(customer.getEmail()),
                "Persistence did not save the customer");
    }

    /**
     * Test deleting Customer object in the persistence layer.
     *
     * @author Jennifer You (jenni4u)
     */
    @Test
    void testCustomerDelete() {
        customer.delete();
        customerRepository.save(customer);
        assertNull(
                customerRepository.findCustomerByEmail("mimi@kittycat.com"),
                "Persistence did not delete the customer");
    }

    /**
     * Test read the Customer object's attributes in the persistence layer.
     *
     * @author Jennifer You (jenni4u)
     */
    @Test
    void testCustomerReadAttributes() {
        assertEquals(
                "meowmeow",
                customer.getPassword(),
                "Persistence did not return the same password attribute");
        assertEquals(
                "123 Cat Street",
                customer.getAddress(),
                "Persistence did not return the same address attribute");
        assertEquals(
                100,
                customer.getNumLoyaltyPoints(),
                "Persistence did not return the same numLoyaltyPoints attribute");
    }

    /**
     * Test changing the Customer object's attributes in the persistence layer.
     *
     * @author Jennifer You (jenni4u)
     */
    @Test
    void testCustomerWriteAttributes() {
        // change attributes
        String newPassword = "woofie";
        String newAddress = "456 Dog Street";
        int newLoyaltyPoints = 200;
        customer.setPassword(newPassword);
        customer.setAddress(newAddress);
        customer.setNumLoyaltyPoints(newLoyaltyPoints);
        customerRepository.save(customer);
        customer = customerRepository.findCustomerByEmail(customer.getEmail());

        // attributes
        assertEquals(
                newPassword,
                customer.getPassword(),
                "Persistence did not update the password attribute");
        assertEquals(
                newAddress,
                customer.getAddress(),
                "Persistence did not update the address attribute");
        assertEquals(
                newLoyaltyPoints,
                customer.getNumLoyaltyPoints(),
                "Persistence did not update the numLoyaltyPoints attribute");
    }

    /**
     * Test read and write of Customer object's references in the persistence layer.
     *
     * @author Jennifer You (jenni4u)
     */
    @Test
    @Transactional
    void testCustomerReferences() {
        // create clothing item
        ClothingItem item = new ClothingItem();
        item.setNumInStock(10);
        item.setColour(ClothingItem.Colour.PINK);
        item.setSize(ClothingItem.Size.M);
        clothingItemRepository.save(item);
        item = clothingItemRepository.findClothingItemById(item.getId());

        // create order
        Order order = new Order();
        order.setState(Order.State.ASSIGNED);
        order.setOrderDate(new Date(2024, 6, 1));
        order.setDeliveryDate(new Date(2024, 6, 15));
        order.setDeliveryAddress("123 Cat Street");
        order.setPrice(50.0f);
        orderRepository.save(order);
        order = orderRepository.findOrderById(order.getId());

        // read references
        assertFalse(
                customer.hasShoppingCart(),
                "Persistence did not return the same shopping cart reference");
        assertFalse(
                customer.hasPurchasedOrders(),
                "Persistence did not return the same purchased orders reference");

        // write references
        customer.addShoppingCart(item);
        customer.addPurchasedOrder(order);
        customerRepository.save(customer);
        customer = customerRepository.findCustomerByEmail(customer.getEmail());
        assertEquals(
                item,
                customer.getShoppingCart(customer.indexOfShoppingCart(item)),
                "Persistence did not update the shopping cart reference");
        assertEquals(
                order,
                customer.getPurchasedOrder(customer.indexOfPurchasedOrder(order)),
                "Persistence did not update the purchased orders reference");

        customer.removePurchasedOrder(order);
        customer.removeShoppingCart(item);
        customerRepository.save(customer);
        assertEquals(
                -1,
                customer.indexOfShoppingCart(item),
                "Persistence did not remove the shopping cart reference");
        assertEquals(
                -1,
                customer.indexOfPurchasedOrder(order),
                "Persistence did not remove the purchased orders reference");
    }
}
