package ca.mcgill.ecse321.fashionstore.repository;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;

import ca.mcgill.ecse321.fashionstore.model.ClothingItem;
import ca.mcgill.ecse321.fashionstore.model.ClothingProduct;
import ca.mcgill.ecse321.fashionstore.model.Customer;
import ca.mcgill.ecse321.fashionstore.model.Order;
import java.sql.Date;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

/** This source class was generated by the Gradle 'init' task. */
@SpringBootTest
class CustomerRepositoryTests {

    /** This source method was generated by the Gradle 'init' task. */
    @Test
    void contextLoads() {
        assertDoesNotThrow(() -> {});
    }

    @Autowired private CustomerRepository customerRepository;
    @Autowired private OrderRepository orderRepository;
    @Autowired private ClothingItemRepository clothingItemRepository;
    @Autowired private ClothingProductRepository clothingProductRepository;

    /**
     * Clear up databases after each test.
     *
     * @author Jennifer You
     */
    @AfterEach
    public void clearDatabase() {
        customerRepository.deleteAll();
        orderRepository.deleteAll();
        clothingItemRepository.deleteAll();
        clothingProductRepository.deleteAll();
    }

    /**
     * Test read and write of the Customer object and its attribute in the persistence layer.
     *
     * @author Jennifer You
     */
    @Test
    void testCustomerPersistence() {
        // Create customer
        String email = "mimi@kittycat.com";
        String password = "meowmeow";
        String address = "123 Cat Street";
        int loyaltyPoints = 100;
        Customer customer = new Customer(email, password, address, loyaltyPoints);
        customerRepository.save(customer);
        // changing attributes
        String newPassword = "woofie";
        String newAddress = "456 Dog Street";
        int newNumLoyaltyPoints = 200;
        // read object and attributes
        assertEquals(
                customer,
                customerRepository.findCustomerByEmail(email),
                "Persistence did not return the same customer");
        assertEquals(
                email, customer.getEmail(), "Persistence did not return the same email attribute");
        assertEquals(
                password,
                customer.getPassword(),
                "Persistence did not return the same password attribute");
        assertEquals(
                address,
                customer.getAddress(),
                "Persistence did not return the same address attribute");
        assertEquals(
                loyaltyPoints,
                customer.getNumLoyaltyPoints(),
                "Persistence did not return the same numLoyaltyPoints attribute");
        // write attributes
        customer.setPassword(newPassword);
        customer.setAddress(newAddress);
        customer.setNumLoyaltyPoints(newNumLoyaltyPoints);
        customer = customerRepository.findCustomerByEmail(email);
        assertEquals(
                newPassword,
                customer.getPassword(),
                "Persistence did not update the password attribute");
        assertEquals(
                newAddress,
                customer.getAddress(),
                "Persistence did not update the address attribute");
        assertEquals(
                newNumLoyaltyPoints,
                customer.getNumLoyaltyPoints(),
                "Persistence did not update the numLoyaltyPoints attribute");
    }

    /**
     * Test read and write of Customer object's references in the persistence layer.
     *
     * @author Jennifer You
     */
    @Test
    void testCustomerReferences() {
        // Create customer
        String aEmail = "mimi@kittycat.com";
        Customer customer = new Customer(aEmail, "meowmeow", "123 Cat Street", 100);
        customerRepository.save(customer);

        // create clothing product
        ClothingProduct product = new ClothingProduct("Shirt", 20.0f);

        // create clothing item
        ClothingItem item =
                new ClothingItem(ClothingItem.Size.S, ClothingItem.Colour.RED, 10, product);

        // create order
        Order order =
                new Order(
                        Order.State.PURCHASED,
                        new Date(System.currentTimeMillis()),
                        new Date(System.currentTimeMillis()),
                        "789 Order Street",
                        50.0f);

        // read references
        customer = customerRepository.findCustomerByEmail(aEmail);
        assertFalse(
                customer.hasShoppingCart(),
                "Persistence did not return the same shopping cart reference");
        assertFalse(
                customer.hasPurchasedOrders(),
                "Persistence did not return the same purchased orders reference");

        // write references
        customer.addShoppingCart(item);
        customer.addPurchasedOrder(order);
        assertEquals(
                item,
                customer.getShoppingCart(customer.indexOfShoppingCart(item)),
                "Persistence did not update the shopping cart reference");
        assertEquals(
                order,
                customer.getPurchasedOrder(customer.indexOfPurchasedOrder(order)),
                "Persistence did not update the purchased orders reference");
    }
}
