package ca.mcgill.ecse321.fashionstore;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

/** This source class was generated by the Gradle 'init' task. */
@SpringBootTest
class FashionStoreApplicationTests {

    /** This source method was generated by the Gradle 'init' task. */
    @Test
    void contextLoads() {
        assertDoesNotThrow(() -> {});
    }


}