package ca.mcgill.ecse321.fashionstore;
import ca.mcgill.ecse321.fashionstore.model.*;
import ca.mcgill.ecse321.fashionstore.repository.*;


import ca.mcgill.ecse321.fashionstore.repository.OrderRepository;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import java.sql.Date;

import static org.junit.jupiter.api.Assertions.*;

/** This source class was generated by the Gradle 'init' task. */
@SpringBootTest
class FashionStoreApplicationTests {

    /** This source method was generated by the Gradle 'init' task. */
    @Test
    void contextLoads() {
        assertDoesNotThrow(() -> {});
    }

    @Autowired private OrderRepository orderRepo;
    @Autowired private CustomerRepository customerRepo;
    @Autowired private EmployeeRepository employeeRepo;
    @Autowired private ClothingItemRepository itemRepo;
    @Autowired private ClothingProductRepository productRepo;

    @AfterEach
    public void clearDatabase() {
        orderRepo.deleteAll();
        customerRepo.deleteAll();
        employeeRepo.deleteAll();
        itemRepo.deleteAll();
        productRepo.deleteAll();
    }

    @Test
    public void testOrderPersistence() {
        // Create ClothingProduct + ClothingItem
        ClothingProduct product = new ClothingProduct("T-Shirt", 29.99f);
        productRepo.save(product);

        ClothingItem item = new ClothingItem(ClothingItem.Size.L, ClothingItem.Colour.BLUE, 5, product);
        itemRepo.save(item);

        // Create Customer + Employee
        Customer customer = new Customer("cust@example.com", "abc", "789 Customer Ln", 10);
        customerRepo.save(customer);

        Employee employee = new Employee("emp2@example.com", "xyz", "101 Worker St", 0);
        employeeRepo.save(employee);

        // Create Order
        Date orderDate = Date.valueOf("2024-01-15");
        Date deliveryDate = Date.valueOf("2024-01-20");

        Order order = new Order(
                Order.State.PURCHASED,
                orderDate,
                deliveryDate,
                "987 Delivery Ave",
                49.99f
        );

        order.addItem(item);
        order.setCustomer(customer);
        order.setEmployee(employee);

        orderRepo.save(order);

        Order loaded = orderRepo.findById(order.getId()).orElse(null);
        assertNotNull(loaded);

        // Attributes
        assertEquals(Order.State.PURCHASED, loaded.getState());
        assertEquals(orderDate, loaded.getOrderDate());
        assertEquals(deliveryDate, loaded.getDeliveryDate());
        assertEquals("987 Delivery Ave", loaded.getDeliveryAddress());
        assertEquals(49.99f, loaded.getPrice());

        // References
        assertEquals(customer.getEmail(), loaded.getCustomer().getEmail());
        assertEquals(employee.getEmail(), loaded.getEmployee().getEmail());
        assertEquals(1, loaded.getItems().size());
        assertEquals(item.getId(), loaded.getItems().get(0).getId());
    }


}
