/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthOrdersRouteImport } from './routes/_auth/orders'
import { Route as AuthAccountRouteImport } from './routes/_auth/account'
import { Route as AuthEmployeeRouteRouteImport } from './routes/_auth/employee/route'
import { Route as AuthCartRouteRouteImport } from './routes/_auth/cart/route'
import { Route as AuthAdminRouteRouteImport } from './routes/_auth/admin/route'
import { Route as AuthProductsIndexRouteImport } from './routes/_auth/products/index'
import { Route as AuthEmployeeIndexRouteImport } from './routes/_auth/employee/index'
import { Route as AuthCartIndexRouteImport } from './routes/_auth/cart/index'
import { Route as AuthAdminIndexRouteImport } from './routes/_auth/admin/index'
import { Route as AuthProductsProductIdRouteImport } from './routes/_auth/products/$productId'
import { Route as AuthAdminOrdersRouteImport } from './routes/_auth/admin/orders'
import { Route as AuthAdminProductsIndexRouteImport } from './routes/_auth/admin/products/index'
import { Route as AuthAdminAccountsIndexRouteImport } from './routes/_auth/admin/accounts/index'
import { Route as AuthAdminProductsProductIdRouteImport } from './routes/_auth/admin/products/$productId'
import { Route as AuthAdminAccountsAccountIdRouteImport } from './routes/_auth/admin/accounts/$accountId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOrdersRoute = AuthOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAccountRoute = AuthAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEmployeeRouteRoute = AuthEmployeeRouteRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCartRouteRoute = AuthCartRouteRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminRouteRoute = AuthAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProductsIndexRoute = AuthProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEmployeeIndexRoute = AuthEmployeeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthEmployeeRouteRoute,
} as any)
const AuthCartIndexRoute = AuthCartIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthCartRouteRoute,
} as any)
const AuthAdminIndexRoute = AuthAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthProductsProductIdRoute = AuthProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminOrdersRoute = AuthAdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthAdminProductsIndexRoute = AuthAdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthAdminAccountsIndexRoute = AuthAdminAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthAdminProductsProductIdRoute =
  AuthAdminProductsProductIdRouteImport.update({
    id: '/products/$productId',
    path: '/products/$productId',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminAccountsAccountIdRoute =
  AuthAdminAccountsAccountIdRouteImport.update({
    id: '/accounts/$accountId',
    path: '/accounts/$accountId',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AuthAdminRouteRouteWithChildren
  '/cart': typeof AuthCartRouteRouteWithChildren
  '/employee': typeof AuthEmployeeRouteRouteWithChildren
  '/account': typeof AuthAccountRoute
  '/orders': typeof AuthOrdersRoute
  '/admin/orders': typeof AuthAdminOrdersRoute
  '/products/$productId': typeof AuthProductsProductIdRoute
  '/admin/': typeof AuthAdminIndexRoute
  '/cart/': typeof AuthCartIndexRoute
  '/employee/': typeof AuthEmployeeIndexRoute
  '/products/': typeof AuthProductsIndexRoute
  '/admin/accounts/$accountId': typeof AuthAdminAccountsAccountIdRoute
  '/admin/products/$productId': typeof AuthAdminProductsProductIdRoute
  '/admin/accounts/': typeof AuthAdminAccountsIndexRoute
  '/admin/products/': typeof AuthAdminProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/account': typeof AuthAccountRoute
  '/orders': typeof AuthOrdersRoute
  '/admin/orders': typeof AuthAdminOrdersRoute
  '/products/$productId': typeof AuthProductsProductIdRoute
  '/admin': typeof AuthAdminIndexRoute
  '/cart': typeof AuthCartIndexRoute
  '/employee': typeof AuthEmployeeIndexRoute
  '/products': typeof AuthProductsIndexRoute
  '/admin/accounts/$accountId': typeof AuthAdminAccountsAccountIdRoute
  '/admin/products/$productId': typeof AuthAdminProductsProductIdRoute
  '/admin/accounts': typeof AuthAdminAccountsIndexRoute
  '/admin/products': typeof AuthAdminProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_auth/admin': typeof AuthAdminRouteRouteWithChildren
  '/_auth/cart': typeof AuthCartRouteRouteWithChildren
  '/_auth/employee': typeof AuthEmployeeRouteRouteWithChildren
  '/_auth/account': typeof AuthAccountRoute
  '/_auth/orders': typeof AuthOrdersRoute
  '/_auth/admin/orders': typeof AuthAdminOrdersRoute
  '/_auth/products/$productId': typeof AuthProductsProductIdRoute
  '/_auth/admin/': typeof AuthAdminIndexRoute
  '/_auth/cart/': typeof AuthCartIndexRoute
  '/_auth/employee/': typeof AuthEmployeeIndexRoute
  '/_auth/products/': typeof AuthProductsIndexRoute
  '/_auth/admin/accounts/$accountId': typeof AuthAdminAccountsAccountIdRoute
  '/_auth/admin/products/$productId': typeof AuthAdminProductsProductIdRoute
  '/_auth/admin/accounts/': typeof AuthAdminAccountsIndexRoute
  '/_auth/admin/products/': typeof AuthAdminProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin'
    | '/cart'
    | '/employee'
    | '/account'
    | '/orders'
    | '/admin/orders'
    | '/products/$productId'
    | '/admin/'
    | '/cart/'
    | '/employee/'
    | '/products/'
    | '/admin/accounts/$accountId'
    | '/admin/products/$productId'
    | '/admin/accounts/'
    | '/admin/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/account'
    | '/orders'
    | '/admin/orders'
    | '/products/$productId'
    | '/admin'
    | '/cart'
    | '/employee'
    | '/products'
    | '/admin/accounts/$accountId'
    | '/admin/products/$productId'
    | '/admin/accounts'
    | '/admin/products'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/register'
    | '/_auth/admin'
    | '/_auth/cart'
    | '/_auth/employee'
    | '/_auth/account'
    | '/_auth/orders'
    | '/_auth/admin/orders'
    | '/_auth/products/$productId'
    | '/_auth/admin/'
    | '/_auth/cart/'
    | '/_auth/employee/'
    | '/_auth/products/'
    | '/_auth/admin/accounts/$accountId'
    | '/_auth/admin/products/$productId'
    | '/_auth/admin/accounts/'
    | '/_auth/admin/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/orders': {
      id: '/_auth/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthOrdersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/account': {
      id: '/_auth/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthAccountRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/employee': {
      id: '/_auth/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof AuthEmployeeRouteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/cart': {
      id: '/_auth/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AuthCartRouteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/products/': {
      id: '/_auth/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthProductsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/employee/': {
      id: '/_auth/employee/'
      path: '/'
      fullPath: '/employee/'
      preLoaderRoute: typeof AuthEmployeeIndexRouteImport
      parentRoute: typeof AuthEmployeeRouteRoute
    }
    '/_auth/cart/': {
      id: '/_auth/cart/'
      path: '/'
      fullPath: '/cart/'
      preLoaderRoute: typeof AuthCartIndexRouteImport
      parentRoute: typeof AuthCartRouteRoute
    }
    '/_auth/admin/': {
      id: '/_auth/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthAdminIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/products/$productId': {
      id: '/_auth/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AuthProductsProductIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/orders': {
      id: '/_auth/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthAdminOrdersRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/products/': {
      id: '/_auth/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AuthAdminProductsIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/accounts/': {
      id: '/_auth/admin/accounts/'
      path: '/accounts'
      fullPath: '/admin/accounts/'
      preLoaderRoute: typeof AuthAdminAccountsIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/products/$productId': {
      id: '/_auth/admin/products/$productId'
      path: '/products/$productId'
      fullPath: '/admin/products/$productId'
      preLoaderRoute: typeof AuthAdminProductsProductIdRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/accounts/$accountId': {
      id: '/_auth/admin/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/admin/accounts/$accountId'
      preLoaderRoute: typeof AuthAdminAccountsAccountIdRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
  }
}

interface AuthAdminRouteRouteChildren {
  AuthAdminOrdersRoute: typeof AuthAdminOrdersRoute
  AuthAdminIndexRoute: typeof AuthAdminIndexRoute
  AuthAdminAccountsAccountIdRoute: typeof AuthAdminAccountsAccountIdRoute
  AuthAdminProductsProductIdRoute: typeof AuthAdminProductsProductIdRoute
  AuthAdminAccountsIndexRoute: typeof AuthAdminAccountsIndexRoute
  AuthAdminProductsIndexRoute: typeof AuthAdminProductsIndexRoute
}

const AuthAdminRouteRouteChildren: AuthAdminRouteRouteChildren = {
  AuthAdminOrdersRoute: AuthAdminOrdersRoute,
  AuthAdminIndexRoute: AuthAdminIndexRoute,
  AuthAdminAccountsAccountIdRoute: AuthAdminAccountsAccountIdRoute,
  AuthAdminProductsProductIdRoute: AuthAdminProductsProductIdRoute,
  AuthAdminAccountsIndexRoute: AuthAdminAccountsIndexRoute,
  AuthAdminProductsIndexRoute: AuthAdminProductsIndexRoute,
}

const AuthAdminRouteRouteWithChildren = AuthAdminRouteRoute._addFileChildren(
  AuthAdminRouteRouteChildren,
)

interface AuthCartRouteRouteChildren {
  AuthCartIndexRoute: typeof AuthCartIndexRoute
}

const AuthCartRouteRouteChildren: AuthCartRouteRouteChildren = {
  AuthCartIndexRoute: AuthCartIndexRoute,
}

const AuthCartRouteRouteWithChildren = AuthCartRouteRoute._addFileChildren(
  AuthCartRouteRouteChildren,
)

interface AuthEmployeeRouteRouteChildren {
  AuthEmployeeIndexRoute: typeof AuthEmployeeIndexRoute
}

const AuthEmployeeRouteRouteChildren: AuthEmployeeRouteRouteChildren = {
  AuthEmployeeIndexRoute: AuthEmployeeIndexRoute,
}

const AuthEmployeeRouteRouteWithChildren =
  AuthEmployeeRouteRoute._addFileChildren(AuthEmployeeRouteRouteChildren)

interface AuthRouteChildren {
  AuthAdminRouteRoute: typeof AuthAdminRouteRouteWithChildren
  AuthCartRouteRoute: typeof AuthCartRouteRouteWithChildren
  AuthEmployeeRouteRoute: typeof AuthEmployeeRouteRouteWithChildren
  AuthAccountRoute: typeof AuthAccountRoute
  AuthOrdersRoute: typeof AuthOrdersRoute
  AuthProductsProductIdRoute: typeof AuthProductsProductIdRoute
  AuthProductsIndexRoute: typeof AuthProductsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminRouteRoute: AuthAdminRouteRouteWithChildren,
  AuthCartRouteRoute: AuthCartRouteRouteWithChildren,
  AuthEmployeeRouteRoute: AuthEmployeeRouteRouteWithChildren,
  AuthAccountRoute: AuthAccountRoute,
  AuthOrdersRoute: AuthOrdersRoute,
  AuthProductsProductIdRoute: AuthProductsProductIdRoute,
  AuthProductsIndexRoute: AuthProductsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
