/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as AuthRouteImport } from "./routes/_auth";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AuthProductsIndexRouteImport } from "./routes/_auth/products/index";
import { Route as AuthAdminIndexRouteImport } from "./routes/_auth/admin/index";

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthProductsIndexRoute = AuthProductsIndexRouteImport.update({
  id: "/products/",
  path: "/products/",
  getParentRoute: () => AuthRoute,
} as any);
const AuthAdminIndexRoute = AuthAdminIndexRouteImport.update({
  id: "/admin/",
  path: "/admin/",
  getParentRoute: () => AuthRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/admin/": typeof AuthAdminIndexRoute;
  "/products/": typeof AuthProductsIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/admin": typeof AuthAdminIndexRoute;
  "/products": typeof AuthProductsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_auth": typeof AuthRouteWithChildren;
  "/login": typeof LoginRoute;
  "/_auth/admin/": typeof AuthAdminIndexRoute;
  "/_auth/products/": typeof AuthProductsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/login" | "/admin/" | "/products/";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/login" | "/admin" | "/products";
  id:
    | "__root__"
    | "/"
    | "/_auth"
    | "/login"
    | "/_auth/admin/"
    | "/_auth/products/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthRoute: typeof AuthRouteWithChildren;
  LoginRoute: typeof LoginRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth": {
      id: "/_auth";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth/products/": {
      id: "/_auth/products/";
      path: "/products";
      fullPath: "/products/";
      preLoaderRoute: typeof AuthProductsIndexRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/admin/": {
      id: "/_auth/admin/";
      path: "/admin";
      fullPath: "/admin/";
      preLoaderRoute: typeof AuthAdminIndexRouteImport;
      parentRoute: typeof AuthRoute;
    };
  }
}

interface AuthRouteChildren {
  AuthAdminIndexRoute: typeof AuthAdminIndexRoute;
  AuthProductsIndexRoute: typeof AuthProductsIndexRoute;
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminIndexRoute: AuthAdminIndexRoute,
  AuthProductsIndexRoute: AuthProductsIndexRoute,
};

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
