name: Build frontend with npm

on:
  push:
    paths-ignore:
      - "**/*.md"
    branches: ["main"]
  pull_request:
    branches: ["main"]
    paths:
      - "frontend/**/*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Build frontend
        run: |
          cd frontend
          npm ci
          npm run build
